#!/bin/zsh

DIR=`pwd`

while [[ `print -l *.cabal(.N)` == "" && `pwd` != $HOME ]] do
  cd ..
done

if [[ `pwd` != $HOME ]] 
then
  cabal $*
else
  echo "This doesn't seem to be a cabalized project."
fi

cd $DIR
