#!/bin/zsh

unzip *.zip

ls *assignsubmission* | cut -f 1 -d '_' | cut -f 2 -d ' ' | sort | uniq | xargs mkdir -p

for f in *assignsubmission*; do
  NAME=${f/_*/}
  NAME=`echo $NAME | cut -f 2 -d ' '`
  FILE=${f/*_assignsubmission_file_/}
  mv $f $NAME/$FILE
done
