#!/bin/zsh

# Simple stopwatch script, copied from https://superuser.com/questions/611538/is-there-a-way-to-display-a-countdown-or-stopwatch-timer-in-a-terminal

date1=`date +%s`; while true; do
   echo -ne "$(date -u --date @$((`date +%s` - $date1)) +%H:%M:%S)\r";
   sleep 0.2
done
