#!/bin/zsh

DIR=`pwd`

while [[ `print -l *.cabal(.N)` == "" && `pwd` != $HOME ]] do
  cd ..
done

if [[ `pwd` != $HOME ]] 
then
  PROJ=`print -l *.cabal(.N) | cut -f1 -d.`
  firefox "file://`pwd`/dist/doc/html/$PROJ/index.html" &
else
  echo "This doesn't seem to be a cabalized project."
fi

cd $DIR
